[project]
name = "b2032-kepler-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "pandas==1.5.3",
    "keplergl-cli==0.3.3"
]
